# Workflow to build the production web app and deploy the production web app and database for Board Board.
name: Build and Deploy

on:
  # Runs on any commits to the main branch
  push:
    branches: ["main"]

  # Allows running this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  actions: write
  id-token: write
  pages: write

# Allow only one concurrent deployment
concurrency:
  group: "build-and-deploy"
  cancel-in-progress: true

jobs:
  # Run Playwright tests before build
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Node
        uses: actions/setup-node@v5
        with:
          node-version: lts/*
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run tests
        run: npx playwright test

      # Upload the test results so they can be examined if necessary
      - name: Upload Playwright HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
  # Build the web app
  build:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      build-status: ${{ steps.build_outcome.outcome }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Node
        uses: actions/setup-node@v5
        with:
          node-version: lts/*
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build app
        id: build_outcome
        run: npm run build

      # Necessary to ensure manual routing works correctly in GitHub Pages
      - name: Copy index.html to 404.html
        if: success()
        run: |
          cp dist/index.html dist/404.html
          echo "Copied index.html to 404.html for GitHub Pages routing support"

      - name: Upload built app
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: build-dist
          path: "./dist"

      - name: Notify build success
        if: success()
        run: echo "✅ Build succeeded!"

      - name: Notify build failed
        if: failure()
        run: echo "❌ Build failed. No deployment will occur."

  # Deploy the web app to GitHub Pages and the database to Supabase in parallel.
  # `fail-fast: true` will cancel all parallel jobs if one fails.
  # Uses production environment to access secrets from the GitHub production environment.
  deploy_matrix:
    needs: build
    environment:
      name: production
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        target: [web, database]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Download build artifact
        if: matrix.target == 'web'
        uses: actions/download-artifact@v4
        with:
          name: build-dist
          path: "./dist"

      # --- Web Deployment ---
      - name: Setup Pages
        if: matrix.target == 'web'
        uses: actions/configure-pages@v5

      - name: Upload Pages Artifact
        if: matrix.target == 'web'
        uses: actions/upload-pages-artifact@v4
        with:
          path: "./dist"

      - name: Deploy to GitHub Pages
        if: matrix.target == 'web'
        id: deployment
        uses: actions/deploy-pages@v4

      # --- Database Deployment ---
      - name: Install Supabase CLI
        if: matrix.target == 'database'
        run: |
          curl -fsSL https://cli.supabase.com/install.sh | sh -s -- -b /usr/local/bin

      - name: Push Supabase migrations to production
        if: matrix.target == 'database'
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
        run: |
          npx supabase link --project-ref ubgqdzmqlnbhqbklotwc --password $SUPABASE_DB_PASSWORD
          npx supabase db push

  # Print results.
  # Prints "✅ Both deployments succeeded!" if both web and database deployments passed.
  # Prints "❌ Deployment failed. Both web & database deploys cancelled or rolled back." if either deployment failed.
  # `if always()` is used to ensure that the results will be printed even if the 'deploy_matrix' job failed.
  finalize:
    needs: deploy_matrix
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Report outcome
        run: |
          if [ "${{ needs.deploy_matrix.result }}" == "success" ]; then
            echo "✅ Both deployments succeeded!"
          else
            echo "❌ Deployment failed. Both web & database deploys cancelled or rolled back."
            exit 1
          fi
